### ISSUE TITLE
`no-cb-test` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-ava#2]
Prevent the use of `test.cb()`. Some projects/companies might want to prevent the use of callback tests in favor of only async functions or returning promises.

**Comment by SamVerschueren** [comment]
I would go for the singular form `no-cb-test`. It looks like (most) [eslint rules](http://eslint.org/docs/rules/) are singular as well.

**Comment by sindresorhus** [comment]
@SamVerschueren :+1:
