### ISSUE TITLE
`no-statement-after-end` rule

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-ava#25]
Rule proposal: Enforce that no statements happen after a `t.end()` is called.

Might be a bit hard to handle if `t.end()` is called conditionnally, but it's worth a try.

**Comment by sindresorhus** [comment]
Not sure if there's a point, as AVA will fail hard if you use `t.end()` in a non-cb test.

**Comment by sindresorhus** [comment]
:+1: http://eslint.org/docs/developer-guide/code-path-analysis.html might help.

**Comment by jfmengels** [comment]
The code path analysis tool look nice, but I can't get my head around it yet ^^'
I may take a shot at it later, If someone wants to take a shot at it, go ahead :)

**Comment by jamestalmage** [comment]
https://github.com/jfmengels/eslint-plugin-ava/commit/f15c22d481a8705555af6c7820c535a97f068238 already has good docs for this, so all wee need now is an implementation.

**Comment by jamestalmage** [comment]
I'm going to give it a shot. @jfmengels - If I can't figure it out in an hour or two, I'm probably not going to get to it for a few days. So just ping me to let me know if you want to start on it again.

**Comment by jfmengels** [comment]
Oops, forgot to unassign myself. Go ahead @jamestalmage, and good luck :)
