### ISSUE TITLE
no-invalid-end rule

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-ava#26]
Rule proposal: Enforce that `t.end()` is not called in a non-`test.cb()` test function.

**Comment by sindresorhus** [comment]
Not sure if there's a point, as AVA will fail hard if you use `t.end()` in a non-cb test.

**Comment by jfmengels** [comment]
Linting can also be used in the text editor while writing code. Having an early warning might prevent some people to scratch their head. Otherwise, I agree with you in the sense that when you run `npm test`, it doesn't provide much (maybe just erroring a bit earlier than normal?).

**Comment by sindresorhus** [comment]
Ah, that's a good point. Early warning in editor makes it worth it.

**Comment by sindresorhus** [comment]
Maybe `no-invalid-end` is a better name? At least shorter.

**Comment by jfmengels** [comment]
Yes, that's better :)
