### ISSUE TITLE
Releasing 1.0.0

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-ava#30]
Hey guys,

`eslint-plugin-ava` has had plenty of new rules (including all the ones listed in the beginning) since its last publication on `npm`. Should we publish it now?
Also, I was wondering whether we should release it as 1.0.0. The project is unlikely to have a breaking change soon, so I'd say it's better to move it to a "normal" semver version before it gets used a lot.

What do you guys think?

**Comment by sindresorhus** [comment]
Yes. Good thought. Already been planning to do a 0.1.0 release for days, but time. I guess 1.0.0 makes more sense though.

**Comment by sindresorhus** [comment]
Done :)

**Comment by jfmengels** [comment]
Thanks!
