### ISSUE TITLE
Check parent directory name

### ISSUE THREAD

**Issue by Spy-Seth** [sindresorhus/eslint-plugin-ava#51]
In a rule check that we do not create a test files (a file containing `import test from 'ava';`?) in a path that is not in an ignored path like `fixtures` or `helpers`. 

- `test/units/foo/myTestFile.js` should not trigger an error 
- `test/units/foo/helpers/myHelper.js` should not trigger an error 
- `test/units/foo/helpers/myTestFile.js` should trigger an error

**Comment by jfmengels** [comment]
Sounds like a good idea to me :+1:.

Would be nice to actually do that for all files that are not in the AVA glob path, be it the default or a custom one.
For instance, I often use `ava "src/**/*.test.js"`. If I instead indicate it as a param of the rule, or even better in the AVA config in the `package.json` file (is that something that is supported already? and could the rule get access to that info?), then it would be nice if the ESLint rule caught the fact that some file would not be run.

Does anyone know whether helpers and fixtures are ignored even when defining a custom glob path?

**Comment by sindresorhus** [comment]
> Does anyone know whether helpers and fixtures are ignored even when defining a custom glob path?

They are.

**Comment by jamestalmage** [comment]
But you can `import 'ava'` in a helper if your helper helps you create tests. I have seen that pattern used, and I don't think there is anything wrong with that. 

I guess in those situations you could just turn off the rule.

**Comment by Spy-Seth** [comment]
In that case you import all AVA our only some part ?
