### ISSUE TITLE
test.title needed for test.before() and friends

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-ava#52]
![image](https://cloud.githubusercontent.com/assets/3869412/14020461/87c6a952-f1d7-11e5-99f0-dde2dca4d0fd.png)
I've been told that not giving a title to a `t.before()` (and friends) triggers the ̀test-title` rule, and I wondered what you guys thought about this. Should we disable this by default for those, and allow them to be enabled with an option?
I don't really see the point of having a title for a before/after, but some might find it useful. Anyway, I think it should be disabled by default at the very least.

**Comment by sindresorhus** [comment]
Yeah, I would just disable it for those. I don't see the use-case of enforcing it, even behind an option.

**Comment by jfmengels** [comment]
Ok, will probably work on it tonight then.

**Comment by godu** [comment]
Don't forget to adapt `no-identical-title` rule.

Ava allows us to set title for before/after hook. We could add a `"strict"`option for `test-title` to enforcing it.

**Comment by sindresorhus** [comment]
> Ava allows us to set title for before/after hook. We could add a "strict"option for test-title to enforcing it.

Yes, but unlike tests, it only makes sense with a title sometimes. We don't add options unless there's some really good real-world use-cases for it. We can consider in the future if there's an actual need.
