### ISSUE TITLE
Change the default option of the `test-title` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-ava#61]
Currently the default is `always`, but I honestly think it would be better to have `if-multiple` as a default.

https://github.com/sindresorhus/eslint-plugin-ava/blob/master/docs/rules/test-title.md

There's really no point in forcing naming a test if there's only one, and if users really want this they can just change the default.

Thoughts?

**Comment by jfmengels** [comment]
I'm fine with it (besides you've already changed it :p)

**Comment by sindresorhus** [comment]
I only changed the recommended preset, not the rule default.

**Comment by jfmengels** [comment]
Ah, my bad. Yeah, that sounds like a good idea.

**Comment by sindresorhus** [comment]
Is there any way in the ESLint option schema to define a default value? Right now we just do it in the code.

http://eslint.org/docs/developer-guide/working-with-rules#options-schemas
http://json-schema.org/

**Comment by jfmengels** [comment]
Not that I could see :/
[ESLint core rules](https://github.com/eslint/eslint/blob/master/lib/rules/arrow-body-style.js#L15) use the in-code style too.

**Comment by sindresorhus** [comment]
I looked into this. JSON Schema supports a [`default` property](http://json-schema.org/latest/json-schema-validation.html#anchor10), but it seems it's [not used by the validator](https://github.com/json-schema/json-schema/issues/5). Atom [supports](https://atom.io/docs/api/v1.6.0/Config) a `default` property, which is very handy. And looks like [ESLint is considering it](https://github.com/eslint/eslint/issues/5418).

For now, I guess we just change the code.
