### ISSUE TITLE
Update the `prefer-power-assert` rule for AVA assert changes

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-ava#62]
https://github.com/sindresorhus/ava/commit/e9c6cc2843e9ee6127aebb2843eafec86cb39bfc
https://github.com/sindresorhus/ava/commit/a7f50eb82d8dae4f9a7e70ae33ef71712a8fd69b

**Comment by jfmengels** [comment]
Do we want to "maintain" the plugin for previous versions of AVA, or only for the latest version? In this case, should we add `t.truthy()` and keep `t.ok()`, or should we replace the latter by the former?

**Comment by sindresorhus** [comment]
Only latest AVA version. Replace the latter by the former.

**Comment by jfmengels** [comment]
Sure, sounds good to me.

**Comment by forresst** [comment]
It would be nice to take the opportunity to also correct the link, replace in `prefer-power-assert.md`:
`You can do [most things] (https://github.com/sindresorhus/ava#enhanced-asserts) with this one`
By:
`You can do [most things] (https://github.com/sindresorhus/ava#enhanced-assertion-messages) with this one`
