### ISSUE TITLE
`no-identical-title` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-ava#7]
Disallow tests with identical titles as it makes it hard to differentiate.

Might be better off in AVA itself: https://github.com/sindresorhus/ava/issues/517

**Comment by jamestalmage** [comment]
> Might be better off in AVA itself

I definitely vote to have it in AVA, but as a warning there. With an ESLint rule, users can configure duplicate tests titles to fail the build.
