### ISSUE TITLE
Two branches?

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-ava#74]
As far as i can tell, we have three types of changes in this repo:
- Bug fixes
- Rule additions/changes for stuff existing in the current version of AVA
- Rule additions/changes for stuff that is yet to land in AVA

For instance https://github.com/sindresorhus/eslint-plugin-ava/pull/71 should probably not be released before the next release of AVA that includes it (be it 0.14.1 or 0.15.0). Rules prohibiting `t.same` and `t.ok` (had we had them before the 0.14 release) also should not be published before 0.14 lands on `npm`.

Should we have two separate branches? One for stuff that can be published right away, and one for stuff that is "on hold"? We can also put merges on hold, but that can be painful for contributors, especially if there are rebase/fixes needed a month after the PR was made.

**Comment by jamestalmage** [comment]
I would like to avoid multiple branches if possible.

- For #71 - we could probably just use `pkg-up` to figure out the AVA version.

- We could hide new rules behind an environment variable:

  ```js
module.exports.rules = {...};

if (process.env.LINT_AVA_NEXT) {
  // mixin additional rules
}
```

- We could set rules as `"off"` until after the AVA release.

I think the last one probably makes the most sense, just set new rules to "off". That won't help #71, but I wonder how many of those we will get.

I am not sure it's that big a problem. The API has been pretty steady (I think I upgraded something from `0.8` the other day - and it just worked - no codemods required).

**Comment by jfmengels** [comment]
> We could set rules as "off" until after the AVA release.

Sounds good.
