### ISSUE TITLE
Prevent incorrect use of `t.throws()`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-ava#75]
I've seen a lot of incorrect use of the `throws` assertion in other test runner and even done the mistake myself sometimes. Now I'm beginning to see it with AVA too, so would be nice to be preemptive about it.

People don't realize they need to wrap their call in a function, so many end up doing `t.throws(foo())` instead of `t.throws(() => foo());`. It's an easy mistake to make.

Happened yesterday: https://github.com/sindresorhus/ava/issues/739

We should disallow doing `t.throws(foo())` and `t.notThrows(foo())`.

I think we can easily add auto-fixing to this by just wrapping the call in an arrow function like so `t.throws(() => foo());`.

**Comment by jamestalmage** [comment]
Unfortunately this won't work.

`foo()` might return a promise, in which case, this `t.throws(foo())` is perfectly acceptable.

**Comment by jamestalmage** [comment]
We could improve things with a custom babel plugin though:

```js
  t.throws(foo());
```

becomes:

```js
t.throws(throwsHelper(function () {
  return foo(a, b);
}, {
  line: 3,
  column: 3,
  source: 'foo()'
});

function throwsHelper(fn, data) {
  try {
     return fn();
  } catch (e) {
     throw new IncorrectThrowsError(e, data);
  }
}
```

**Comment by jfmengels** [comment]
That wouldn't work for nested functions, would it?
```js
function foo(value) {
  return function() {
    // ...
  };
}

t.throws(foo(2)); // valid and proper use
t.throws(foo); // valid but not the expected use
```

You could force the user to give a non-call expression to throws
```js
const fn = foo(2);
t.throws(fn);
```
But that sounds error-prone too and feels like just moving the problem somewhere else.
I feel the pain, but I don't

**Comment by twada** [comment]
For Promises, how about composing small helper function such as [assert-exception](https://github.com/59naga/assert-exception#rejectspromise---promisereason) with `t.truthy`

- `t.truthy(rejects(foo()))`

Or introduce `t.rejects` ?

- `t.rejects(foo())`

Then disallow doing `t.throws(foo())` and `t.notThrows(foo())`.

**Comment by jamestalmage** [comment]
> That wouldn't work for nested functions, would it?

Yeah - it always would.

Take your examples.

```js
t.throws(foo(2)); // valid and proper use
```

becomes:

```js
t.throws(helper(function () {
  return foo(2);
}));
```

----

```js
t.throws(foo); // valid but not the expected use
```


becomes:

```js
t.throws(helper(function () {
  return foo;
}));
```

--- 


We are always just returning the evaluation of the expression. (i.e. we make no change to the value the assertion sees).

The only thing we protect against is a synchronous throw (and by protect, all I mean is we fail with a graceful error message that explains what they did wront).

**Comment by jfmengels** [comment]
@jamestalmage Ah ok, you're just wrapping the call in an extra layer of try-catch :+1:

**Comment by jamestalmage** [comment]
> @jamestalmage Ah ok, you're just wrapping the call in an extra layer of try-catch :+1:

Yes. I decided to say that in the most verbose way possible!

**Comment by jfmengels** [comment]
And you did well, now I got it ;)

**Comment by sindresorhus** [comment]
@jamestalmage Using a Babel helper plugin is a really cool idea! Wonder if we can prevent/improve upon any other usage with Babel helpers.

-

For posterity:

- https://github.com/sindresorhus/ava/pull/742
- https://github.com/jamestalmage/babel-plugin-ava-throws-helper

**Comment by jfmengels** [comment]
Should we close this issue? I have the impression that we can't do much statically.

**Comment by sindresorhus** [comment]
Yup
