### ISSUE TITLE
Usage with async/await

### ISSUE THREAD

**Issue by vitalets** [sindresorhus/eslint-plugin-ava#76]
hi
I'm trying to use this plugin for eslint my test files but getting error:
`Parsing error: Unexpected token t`
My test is using async:
```js
test('resolve issues', async t => {
 ...
}
```
My eslint config is:
```
{
  "extends": "plugin:ava/recommended",
  "plugins": [
    "ava"
  ]
}
```
I suppose it will overwirte parser options so that it will use babel-eslint-parser for tests. 
Could you suggest what should I do to run eslint over my tests?
thx!

**Comment by sindresorhus** [comment]
The default ESLint parser unfortunately doesn't support async functions, so you'll have to use [`babel-eslint`](https://github.com/babel/babel-eslint). We should document that in the readme.

**Comment by vitalets** [comment]
thanks for explanation @sindresorhus !
btw, could you point how to extract babel rules used by ava to use the same for parsing for eslint?

**Comment by novemberborn** [comment]
@vitalets [this is what I use in my eslint](https://github.com/novemberborn/as-i-preach/blob/139abcc151b3a455556390a67f8a554a247b333e/eslintrc.json#L3:L9)

**Comment by vitalets** [comment]
thank you @novemberborn , it works!

**Comment by novemberborn** [comment]
@vitalets cool!

**Comment by ntwb** [comment]
Having just come across this issue, ESLint 3.6 now supports async functions

Add `"ecmaVersion": 8` to your ESLint config `parserOptions`:

    "parserOptions": {
        "ecmaVersion": 8 // or 2017
    },
