### ISSUE TITLE
`prefer-power-assert` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-ava#9]
Only allow use of the assertions that have no `power-assert` alternative:

- `t.ok()` *(You can do most things with this one)*
- `t.throws()`
- `t.notThrows()`,
- `t.same()`
- `t.notSame()`

Useful for people wanting to fully embrace the power of `power-assert`.

**Comment by sindresorhus** [comment]
@twada Does this look correct? Do you know anyone that might be interested in contributing such rule?

**Comment by twada** [comment]
@sindresorhus Cool!

In addition to them,

- `t.pass([message])`
- `t.fail([message])`

should be allowed?

(The same thing could be done by `t.ok(true, [message])` though)

> Do you know anyone that might be interested in contributing such rule?

Okay I'll contribute.

**Comment by sindresorhus** [comment]
> In addition to them, t.pass([message]) t.fail([message])

:+1: Yes, forgot those.
